apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prod
  name: webdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prod
    spec:
      containers:
      - image: gambitmis/web-demo:t1v1
        name: web-demo
        ports:
        - containerPort: 80
        resources: {}
      initContainers:
      - image: busybox
        name: delay
        command: ['sh', '-c', 'echo The app is running! && sleep 10']
status: {}
